import { Navbar, Footer } from '@/components';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeContextProvider } from '@/context/ThemeContext/ThemeContex';
import { ThemeProvider } from '@/providers/ThemeProvider/ThemeProvider';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeContextProvider>
					<ThemeProvider>
						<div className='wrapper'>
							<div className='container'>
								<Navbar id='navbar'/>
								<main id='body'>{children}</main>
								<Footer id='footer'/>
							</div>
						</div>
					</ThemeProvider>
				</ThemeContextProvider>
			</body>

		</html>
	);
}
